-- GENERATED by tools/ddl_sqlite.py from migrations/pg/0002_import_detail.sql. Do not edit;
-- edit the PostgreSQL migration and regenerate.
ALTER TABLE import_provenance ADD COLUMN detail TEXT CHECK (json_valid(detail));
