-- GENERATED by tools/ddl_sqlite.py from migrations/pg/0003_entry.sql. Do not edit;
-- edit the PostgreSQL migration and regenerate.
ALTER TABLE irradiation ADD COLUMN kind TEXT NOT NULL DEFAULT 'irradiation' CHECK (kind IN ('irradiation','package'));
CREATE INDEX sample_name_lower_ix ON sample (lower(name));
CREATE INDEX project_name_lower_ix ON project (lower(name));
