-- GENERATED by tools/ddl_sqlite.py from migrations/pg/0004_sample_geometry.sql. Do not edit;
-- edit the PostgreSQL migration and regenerate.
ALTER TABLE sample ADD COLUMN geom TEXT CHECK (geom LIKE 'SRID=4326;POINT(% %)');
UPDATE sample SET geom = 'SRID=4326;POINT(' || lon || ' ' || lat || ')' WHERE lat IS NOT NULL AND lon IS NOT NULL;
ALTER TABLE sample DROP COLUMN lat;
ALTER TABLE sample DROP COLUMN lon;
