-- GENERATED by tools/ddl_sqlite.py from migrations/pg/0005_ref_scope_indexes.sql. Do not edit;
-- edit the PostgreSQL migration and regenerate.
CREATE INDEX ref_object_position_ix ON ref_object (position_uuid) WHERE position_uuid IS NOT NULL;
CREATE INDEX ref_object_level_ix ON ref_object (level_uuid) WHERE level_uuid IS NOT NULL;
CREATE INDEX ref_object_irradiation_ix ON ref_object (irradiation_uuid) WHERE irradiation_uuid IS NOT NULL;
CREATE INDEX ref_object_mass_spectrometer_ix ON ref_object (mass_spectrometer_uuid) WHERE mass_spectrometer_uuid IS NOT NULL;
