#pragma once

// The DVC store: one access layer over PostgreSQL (shared lab database) and
// SQLite (tests, offline export). DVC schema spec, section 12.2.
//
// Thread model: an IStore and every unit of work it hands out belong to the
// thread that opened the store. Open one store per thread for concurrent use.
// No driver exception crosses this interface; failures are Result errors and a
// lost compare-and-swap is a value (CommitOutcome holding conflicts).

#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "pychron/core/error.hpp"
#include "pychron/persistence/blob.hpp"
#include "pychron/persistence/ids.hpp"
#include "pychron/persistence/model.hpp"

namespace pychron::persistence {

enum class Dialect { PostgreSql, Sqlite };

struct StoreConfig {
  // "sqlite::memory:", "sqlite:/path/to/file.db",
  // "postgresql://user:password@host:port/dbname[?sslmode=verify-full&sslrootcert=...&search_path=...]"
  std::string url;
  // Apply pending migrations on open. Off: refuse to open an outdated schema.
  bool migrate = true;
};

struct Actor {
  Uuid user;
  Uuid client;
};

// ---------------------------------------------------------------- writes (5.4)

struct Conflict {
  Uuid subject;
  Kind kind = Kind::Intercepts;
  std::optional<Uuid> expected;
  std::optional<Uuid> actual;
  std::optional<ChangesetInfo> actual_by;  // the changeset that moved the head to `actual`
};

struct Committed {
  Uuid changeset;
  ChangeSeq seq = 0;
};

// A lost CAS race is an expected outcome, not an Error. Nothing of a
// conflicted changeset persists.
using CommitOutcome = std::variant<Committed, std::vector<Conflict>>;

class IUnitOfWork {
 public:
  virtual ~IUnitOfWork() = default;

  // Stages a revision whose parent is `expected_head` and a head move from
  // `expected_head` to it (nullopt: the first head of this subject and kind).
  // Returns the revision's client-generated id.
  virtual Result<Uuid> add_revision(Uuid subject, Kind kind, RevisionPayload payload,
                                    std::optional<Uuid> expected_head) = 0;
  // Stages a head move to an existing revision (rollback, collection restore).
  virtual Result<void> move_head(Uuid subject, Kind kind, std::optional<Uuid> expected, Uuid to,
                                 MoveReason reason) = 0;
  // One transaction: changeset, revisions and payloads, CAS head moves in
  // (subject, kind) order, head_move rows, change cursor. Consumes the staging.
  virtual Result<CommitOutcome> commit(ChangesetKind kind, std::string message) = 0;
};

// ---------------------------------------------------------------- catalog

struct ClientRegistration {
  std::string hostname;
  std::string role;  // acquisition | reduction | viewer | publisher | importer | admin
  std::optional<Uuid> mass_spectrometer;
  std::string software_version;
};

struct MassSpectrometerSpec {
  std::string name;
  std::optional<std::string> kind;
  std::optional<std::string> code;
};

struct IdentifierSpec {
  std::string identifier;
  std::string kind = "unknown";               // unknown | special
  std::optional<std::string> analysis_type;  // required for special identifiers
  std::optional<Uuid> mass_spectrometer;
};

// ---------------------------------------------------------------- ingest (5.3, 8.3)

struct IsotopeRow {
  std::string isotope;
  std::string detector;
  std::optional<std::string> units, detector_serial, classification;
  std::optional<double> classification_probability;
};

struct DetectorRow {
  std::string detector;
  std::optional<double> deflection, gain_used;
};

struct ExtractionFields {
  std::optional<double> extract_value;
  std::optional<std::string> extract_units;
  std::optional<double> extract_duration, cleanup_duration, pre_cleanup, post_cleanup, cryo_temperature, weight,
      beam_diameter;
  std::optional<std::string> pattern;
  std::optional<double> ramp_duration, ramp_rate, light_value;
  std::optional<std::string> tray;
};

// The root revisions of a new analysis, one per collection kind (I3).
struct CollectionRoots {
  Uuid signals, intercepts, baselines, blanks, icfactors, tags;
  SignalRefs signal_refs;
  Intercepts intercepts_rows;
  Baselines baselines_rows;
  Blanks blanks_rows;
  IcFactors icfactors_rows;
  TagValue tag{"ok", std::nullopt, std::nullopt};
};

// An acquired analysis. Catalog rows are named by natural key (section 3.8);
// every server row id is generated by the acquisition client, so re-sending
// the same item cannot create a second copy of anything.
struct AnalysisIngest {
  Uuid analysis;
  Uuid changeset;
  UtcTime created;  // client clock, stamped on the changeset and revisions

  std::string identifier;
  int aliquot = 0;
  int increment = -1;  // -1: no step
  std::string analysis_type;
  std::optional<std::string> experiment_type;
  UtcTime timestamp;
  std::optional<UtcTime> time_zero;
  std::string mass_spectrometer;
  std::optional<std::string> extract_device;
  ExtractionFields extraction;
  std::optional<std::string> load_name, load_holder;
  std::optional<int> run_index;
  std::optional<std::string> laboratory, instrument_name;
  std::string analyst;  // app_user name, created if missing
  std::optional<Sha256Digest> record_sha256;
  int record_schema_version = 1;

  std::vector<IsotopeRow> isotopes;
  std::vector<DetectorRow> detectors;
  CollectionRoots roots;
};

// One content-addressed raw series.
struct BlobIngest {
  std::string codec;
  Bytes bytes;
  std::optional<int> n_points;
};

struct IngestItem {
  Uuid item;                    // idempotency key
  Sha256Digest payload_sha256;  // of the canonical outbox payload
  Uuid client;
  std::variant<AnalysisIngest, BlobIngest> body;
};

struct IngestAck {
  std::optional<ChangeSeq> change_seq;  // nullopt when nothing changed (a blob already present)
  bool duplicate = false;               // the item had already been ingested
};

// ---------------------------------------------------------------- reads

struct AnalysisSummary {
  Uuid uuid;
  std::string runid;
  std::string identifier;
  int aliquot = 0;
  int increment = -1;
  bool provisional = false;
  std::string analysis_type;
  UtcTime timestamp;
  std::string mass_spectrometer;
  std::string signals_state;  // pending | complete
};

struct AnalysisQuery {
  std::optional<std::string> identifier;
  std::optional<std::string> mass_spectrometer;
  std::optional<std::string> analysis_type;
  std::optional<UtcTime> from, to;  // timestamp_utc range, inclusive
  int limit = 500;
};

struct AnalysisView {
  AnalysisSummary summary;
  std::vector<HeadInfo> heads;
  std::map<Kind, RevisionPayload> payloads;  // at the heads
};

struct ChangeEntity {
  std::string entity_type;
  Uuid entity;
  std::string op;
};

struct ChangeEntry {
  ChangeSeq seq = 0;
  UtcTime committed;
  std::optional<Uuid> changeset;
  Uuid client;
  std::string kind;  // changeset | ingest | blob_complete | catalog | lease
  std::vector<ChangeEntity> entities;
};

struct ChangePage {
  std::vector<ChangeEntry> entries;
  ChangeSeq cursor = 0;  // the last seq in this page, or the input cursor if empty
  bool more = false;
};

struct AppliedMigration {
  int version = 0;
  std::string description;
  std::string checksum_hex;
};

class IStore {
 public:
  virtual ~IStore() = default;

  virtual Dialect dialect() const noexcept = 0;
  virtual Result<std::vector<AppliedMigration>> schema_status() = 0;

  virtual Result<std::unique_ptr<IUnitOfWork>> begin(const Actor& actor) = 0;

  // Catalog (not revisioned; every write is in change_entity with a field diff, D6).
  virtual Result<Uuid> register_client(const ClientRegistration& registration) = 0;
  virtual Result<Uuid> ensure_user(Uuid client, const std::string& name) = 0;
  virtual Result<Uuid> add_mass_spectrometer(Uuid client, const MassSpectrometerSpec& spec) = 0;
  virtual Result<Uuid> add_identifier(Uuid client, const IdentifierSpec& spec) = 0;

  // Idempotent ingest of one outbox item (I7). Used by the uploader.
  virtual Result<IngestAck> ingest(const IngestItem& item) = 0;

  virtual Result<std::optional<Uuid>> head(Uuid subject, Kind kind) = 0;
  virtual Result<std::vector<HeadInfo>> heads(Uuid subject) = 0;
  // Every revision of (subject, kind), oldest first by change_seq.
  virtual Result<std::vector<RevisionInfo>> history(Uuid subject, Kind kind) = 0;
  virtual Result<std::optional<RevisionPayload>> load_payload(Uuid revision) = 0;
  virtual Result<std::optional<AnalysisView>> load_analysis(Uuid analysis) = 0;
  virtual Result<std::vector<AnalysisSummary>> find_analyses(const AnalysisQuery& query) = 0;
  virtual Result<ChangePage> changes_since(ChangeSeq cursor, int limit) = 0;
};

Result<std::unique_ptr<IStore>> open_store(const StoreConfig& config);

// identifier + "-" + two-digit aliquot + step letters (A..Z, AA, ...), as
// legacy make_runid.
std::string make_runid(const std::string& identifier, int aliquot, int increment);

}  // namespace pychron::persistence
