#!/usr/bin/env python3
"""Reference numbers for the least-squares flux models (design section 5.3).

Regenerate tests/reduction/flux_golden.hpp with

    python3 tools/flux_reference.py > tests/reduction/flux_golden.hpp

The formulas are written out directly with numpy (no regression library), so
the C++ solver is checked against an independent implementation. Not run in CI;
prints only the header.
"""
import math

import numpy as np

OFFSETS = np.array([+2, -1, +3, -2, +1, -3, +2, -1]) * 1e-7
SIGMAS = np.array([2, 3, 2, 4, 2, 3, 2, 4]) * 1e-7
POINTS = [(0.0, 0.0), (5.0, 5.0), (-7.0, 2.0), (10.0, 0.0)]



def holes(radii):
    x = np.array([r * math.cos(math.radians(45 * i)) for i, r in enumerate(radii)])
    y = np.array([r * math.sin(math.radians(45 * i)) for i, r in enumerate(radii)])
    return x, y, 1e-3 * (1 + 0.002 * x - 0.001 * y) + OFFSETS


# The ring: every hole at radius 10. A bowl cannot be fitted to it (x^2 + y^2
# is constant, so it is collinear with the constant column), so the bowl cases
# use the "mixed" set, whose holes alternate between radius 10 and 5.
SETS = {"ring": holes([10.0] * 8), "mixed": holes([10.0, 5.0] * 4)}


def design(kind, x, y, degree):
    x, y = np.atleast_1d(x), np.atleast_1d(y)
    one = np.ones_like(x)
    if kind == "plane":
        return np.column_stack([x, y, one])
    if kind == "bowl":
        return np.column_stack([x * x, y * y, x, y, one])
    t = x if kind == "x" else y
    return np.column_stack([t ** p for p in range(degree, -1, -1)])


def fit(kind, weighted, error, degree=1, which="ring"):
    MX, MY, MJ = SETS[which]
    X = design(kind, MX, MY, degree)
    n, q = X.shape
    w = 1.0 / SIGMAS ** 2 if weighted else np.ones(n)
    W = np.diag(w)
    C = np.linalg.inv(X.T @ W @ X)
    beta = C @ X.T @ W @ MJ
    r = MJ - X @ beta
    s2 = (r @ W @ r) / (n - q)
    mswd = np.sum((r / SIGMAS) ** 2) / (n - q)
    j, e = [], []
    for px, py in POINTS:
        xr = design(kind, px, py, degree)[0]
        v = xr @ C @ xr
        if weighted:
            v = v * max(s2, 1.0) if error == "msem" else v
        else:
            v = s2 * v
        j.append(float(xr @ beta))
        e.append(math.sqrt(v))
    return beta, mswd, n - q, j, e


# name, model kind, weighted, error, axis, degree
CASES = [
    ("plane_unweighted_sem", "plane", False, "sem", "x", 1),
    ("plane_weighted_sem", "plane", True, "sem", "x", 1),
    ("plane_weighted_msem", "plane", True, "msem", "x", 1),
    ("bowl_unweighted_sem", "bowl", False, "sem", "x", 1),
    ("bowl_weighted_msem", "bowl", True, "msem", "x", 1),
    ("ls1d_x_degree1_weighted_msem", "x", True, "msem", "x", 1),
    ("ls1d_y_degree2_unweighted_sem", "y", False, "sem", "y", 2),
]


def arr(values):
    return ", ".join(repr(float(v)) for v in values)


print("// Reference numbers for the least-squares flux models.")
print("// Generated by tools/flux_reference.py (numpy):")
print("//   python3 tools/flux_reference.py > tests/reduction/flux_golden.hpp")
print("// kRing: eight holes at radius 10 (plane, 1-D cases). kMixed: radius 10 and 5 alternating")
print("// (bowl cases: a bowl is singular on a single ring). Do not edit by hand.")
print("#pragma once")
print()
print("#include <vector>")
print()
print("namespace flux_golden {")
print()
print("struct MonitorRow {")
print("  const char* label;")
print("  double x, y, j, j_err;")
print("};")
print("struct PointRow {")
print("  double x, y;")
print("};")
print("struct Case {")
print("  const char* name;")
print("  const char* model;  // plane | bowl | ls1d")
print("  bool weighted;")
print("  const char* error;  // sem | msem")
print("  const char* axis;   // x | y (ls1d)")
print("  int degree;         // ls1d")
print("  std::vector<double> parameters;")
print("  double mswd;")
print("  int dof;")
print("  double j[4];")
print("  double j_err[4];")
print("};")
print()
for which, array in (("ring", "kRing"), ("mixed", "kMixed")):
    MX, MY, MJ = SETS[which]
    print(f"inline const MonitorRow {array}[8] = {{")
    for i in range(8):
        print(f'    {{"m{i}", {float(MX[i])!r}, {float(MY[i])!r}, {float(MJ[i])!r}, {float(SIGMAS[i])!r}}},')
    print("};")
    print()
print("inline const PointRow kPoints[4] = {")
for px, py in POINTS:
    print(f"    {{{px!r}, {py!r}}},")
print("};")
print()
print("inline const std::vector<Case> kCases = {")
for name, kind, weighted, error, axis, degree in CASES:
    which = "mixed" if kind == "bowl" else "ring"
    beta, mswd, dof, j, e = fit(kind, weighted, error, degree, which)
    model = kind if kind in ("plane", "bowl") else "ls1d"
    print("    {")
    print(f'        "{name}", "{model}", {"true" if weighted else "false"}, "{error}", "{axis}", {degree},')
    print(f"        {{{arr(beta)}}},")
    print(f"        {float(mswd)!r}, {dof},")
    print(f"        {{{arr(j)}}},")
    print(f"        {{{arr(e)}}},")
    print("    },")
print("};")
print()
print("}  // namespace flux_golden")
